{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agentorchestration.fullname" . }}
  labels:
    {{- include "agentorchestration.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    {{- if .Values.ingress.console.tls.enabled }}
    - hosts:
        - {{ .Values.ingress.console.host }}
      secretName: {{ .Values.ingress.console.tls.secretName }}
    {{- end }}
    {{- if .Values.ingress.todos.tls.enabled }}
    - hosts:
        - {{ .Values.ingress.todos.host }}
      secretName: {{ .Values.ingress.todos.tls.secretName }}
    {{- end }}
  rules:
    - host: {{ .Values.ingress.console.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "agentorchestration.frontendSvcName" . }}
                port:
                  name: http
    - host: {{ .Values.ingress.todos.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "agentorchestration.todosUiSvcName" . }}
                port:
                  name: http
{{- end }}
